FROM registry.access.redhat.com/rhscl/nginx-16-rhel7 

RUN mv /opt/rh/nginx16/root/etc/nginx/nginx.conf /opt/rh/nginx16/root/etc/nginx/nginx.conf.orig

ADD nginx.conf /opt/rh/nginx16/root/etc/nginx/ 
